### ISSUE TITLE
Cannot compile on RN 0.73

### ISSUE THREAD

**Issue by luicfrr** [Tarikjrh/vision-camera-face-detector-v3#3]
I'm using RN 0.73.2 and got this error when compiling my app:
```
Task :vision-camera-face-detector-v3:compileDebugJavaWithJavac FAILED
....../mobile/node_modules/vision-camera-face-detector-v3/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPlugin.java:198: error: constructor FrameProcessorPlugin in class FrameProcessorPlugin cannot be applied to given types;
    super(options);
    ^
  required: no arguments
  found:    Map<String,Object>
  reason: actual and formal argument lists differ in length
......./mobile/node_modules/vision-camera-face-detector-v3/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPluginPackage.java:18: error: incompatible types: incompatible parameter types in lambda expression
    FrameProcessorPluginRegistry.addFrameProcessorPlugin("detectFaces", options -> new VisionCameraFaceDetectorPlugin(options));
                                                                        ^
......../mobile/node_modules/vision-camera-face-detector-v3/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPluginPackage.java:18: error: incompatible types: VisionCameraProxy cannot be converted to Map<String,Object>
    FrameProcessorPluginRegistry.addFrameProcessorPlugin("detectFaces", options -> new VisionCameraFaceDetectorPlugin(options));
                                                                                                                      ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors
```

Using `react-native-vision-camera: 3.8.2`

**Comment by levepic** [comment]
Same problem on RN 0.70!
